[package]
name = "mdast2minimad"
description = "A crate for converting markdown AST to minimad texts"
readme = "README.md"
repository = "https://github.com/zannabianca1997/mdast2minimad"
version = "0.1.0"
edition = "2021"
license = "MIT"
categories = ["text-processing"]
keywords = ["termimad", "markdown", "conversion", "mdast", "minimad"]


[dependencies]
minimad = "0.13.1"
markdown = "1.0.0-alpha.21"
derive_more = { version = "1.0.0", features = [
    "error",
    "display",
    "from",
    "debug",
] }

[dev-dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
termimad = "0.30"

[build-dependencies]
proc-macro2 = "1.0"
quote = "1.0"
slugify = "0.1"
