#![doc = include_str!("../README.md")]

use std::mem;

use derive_more::derive::Debug;
pub use markdown::mdast;
use minimad::{Composite, Compound, Line};

mod configs;
mod errors;
mod supported_nodes;

pub use configs::*;
pub use errors::*;

/// Convert the markdown AST to a minimad Text
///
/// This is the main function of this crate.
/// ```
/// # use markdown::to_mdast;
/// # use termimad::*;
/// # use mdast2minimad::*;
/// let ast = to_mdast("This is *markdown*!", &md_parse_options()).unwrap();
///
/// // Here you can freely modify the ast
///
/// let text = to_minimad(&ast).unwrap();
///
/// // Display it with [`termimad`]
/// println!("{}", FmtText::from_text(&MadSkin::default(), text, None))
/// ```
///
/// The text borrows from the original AST, both for avoid copy and because [`minimad`] is structured like that.
pub fn to_minimad(ast: &mdast::Node) -> Result<minimad::Text, ToMinimadError> {
    let mut emitter = Emitter::new(Configs::default());
    emitter.emit(ast)?;
    Ok(emitter.finish())
}

/// Convert the markdown AST to a minimad Text, with custom options.
///
/// ```
/// # use markdown::to_mdast;
/// # use termimad::*;
/// # use mdast2minimad::*;
/// let ast = to_mdast("This is *markdown*, with [links]!", &md_parse_options()).unwrap();
///
/// // Here you can freely modify the ast
///
/// // Put the link in italic
/// let text = to_custom_minimad(&ast, Configs {
///     links_style: Style {
///         italic: Some(true),
///         ..Default::default()
///     },
///     ..Default::default()
/// }).unwrap();
///
/// // Display it with [`termimad`]
/// println!("{}", FmtText::from_text(&MadSkin::default(), text, None))
/// ```
///
/// The text borrows from the original AST, both for avoid copy and because [`minimad`] is structured like that.
pub fn to_custom_minimad(
    ast: &mdast::Node,
    configs: Configs,
) -> Result<minimad::Text, ToMinimadError> {
    let mut emitter = Emitter::new(configs);
    emitter.emit(ast)?;
    Ok(emitter.finish())
}

/// Return the [`markdown::ParseOptions`] containing all the constructs supported by the conversion
///
/// If the ast is generated by [`markdown::to_mdast`] using these then [`to_minimad`] should never fail,
/// and if it does it should be reported as a bug.
pub const fn md_parse_options() -> markdown::ParseOptions {
    markdown::ParseOptions {
        constructs: markdown::Constructs {
            attention: true,
            autolink: true,
            block_quote: true,
            character_escape: true,
            character_reference: true,
            code_indented: true,
            code_fenced: true,
            code_text: true,
            definition: false,
            frontmatter: false,
            gfm_autolink_literal: true,
            gfm_footnote_definition: false,
            gfm_label_start_footnote: false,
            gfm_strikethrough: true,
            gfm_table: true,
            gfm_task_list_item: false,
            hard_break_escape: true,
            hard_break_trailing: true,
            heading_atx: true,
            heading_setext: true,
            html_flow: false,
            html_text: false,
            label_start_image: false,
            label_start_link: true,
            label_end: true,
            list_item: true,
            math_flow: false,
            math_text: false,
            mdx_esm: false,
            mdx_expression_flow: false,
            mdx_expression_text: false,
            mdx_jsx_flow: false,
            mdx_jsx_text: false,
            thematic_break: true,
        },
        gfm_strikethrough_single_tilde: false,
        math_text_single_dollar: false,
        mdx_expression_parse: None,
        mdx_esm_parse: None,
    }
}

/// Represent the current content model of the emitter
#[derive(Debug, Clone, PartialEq, Eq)]
enum ContentModel<'a> {
    /// Flow content represent the sections of document.
    Flow {
        /// If the last flow element need spacing
        spacing: bool,
    },
    /// Phrasing content represent the text in a document, and its markup.
    Phrasing {
        /// Style of the lines
        style: minimad::CompositeStyle,
        /// Line being built
        compounds: Vec<minimad::Compound<'a>>,
    },
}
impl ContentModel<'_> {
    /// Return if a spacing line must be inserted
    fn need_spacing(&self) -> bool {
        match self {
            ContentModel::Flow { spacing } => *spacing,
            ContentModel::Phrasing { .. } => {
                // Spacing has no sense between phrasing elements.
                // Should appear only in invalid ASTs
                // Defaulting to not giving it
                false
            }
        }
    }

    fn set_spacing(&mut self, new_spacing: bool) {
        match self {
            ContentModel::Flow { spacing } => *spacing = new_spacing,
            ContentModel::Phrasing { .. } => {
                // Here the spacing has no sense.
                // Should appear only in invalid ASTs
            }
        }
    }
}

/// Represent the current style of the emitter
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
struct CurrentStyle {
    bold: bool,
    italic: bool,
    strikeout: bool,
}

/// Minimad code emitter
///
/// This struct builds a [`minimad::Text`] from [`mdast::Node`].
/// It can be used to emit multiple nodes to the same text.
///
/// ```
/// # use markdown::to_mdast;
/// # use termimad::*;
/// # use mdast2minimad::*;
/// let ast1 = to_mdast("This is *markdown*!", &md_parse_options()).unwrap();
/// let ast2 = to_mdast("This is also _markdown_!", &md_parse_options()).unwrap();
///
/// let mut emitter = Emitter::new(Configs::default());
///
/// emitter.emit(&ast1);
/// emitter.emit(&ast2);
///
/// let text = emitter.finish();
///
/// // Display it with [`termimad`]
/// println!("{}", FmtText::from_text(&MadSkin::default(), text, None))
/// ```
///
/// Usually one use the wrapping functions [`to_minimad`] and [`to_custom_minimad`].
pub struct Emitter<'a> {
    /// Lines already emitted
    lines: Vec<minimad::Line<'a>>,
    /// Current content model
    model: Option<ContentModel<'a>>,
    /// Current style of the emitter
    style: CurrentStyle,
    /// Conversion options
    options: Configs,
}

// --- Emitter API ---

impl<'a> Emitter<'a> {
    /// Create a new, empty emitter using the given options
    pub fn new(options: Configs) -> Self {
        Self {
            lines: vec![],
            model: None,
            style: CurrentStyle::default(),
            options,
        }
    }

    /// Complete the emission and return the emitted text
    pub fn finish(mut self) -> minimad::Text<'a> {
        // emit last text if a line is still open
        if let Some(ContentModel::Phrasing { style, compounds }) = self.model {
            self.lines
                .push(Line::Normal(Composite { style, compounds }))
        }
        minimad::Text { lines: self.lines }
    }

    /// Emit an arbitrary node
    ///
    /// Usually this function will be called once on the root node.
    /// If this function is called again, the resulting text will be concatenated.
    pub fn emit(&mut self, node: &'a mdast::Node) -> Result<(), ToMinimadError> {
        // emit the node
        match node {
            mdast::Node::Root(root) => self.root(root),
            mdast::Node::Heading(heading) => self.heading(heading),
            mdast::Node::Text(text) => self.text(text),
            mdast::Node::Paragraph(paragraph) => self.paragraph(paragraph),
            mdast::Node::Code(code) => self.code(code),
            mdast::Node::Strong(strong) => self.strong(strong),
            mdast::Node::Emphasis(emphasis) => self.emphasis(emphasis),
            mdast::Node::InlineCode(inline_code) => self.inline_code(inline_code),
            mdast::Node::Delete(delete) => self.delete(delete),
            mdast::Node::Link(link) => self.link(link),
            mdast::Node::List(list) => self.list(list),
            mdast::Node::Table(table) => self.table(table),
            mdast::Node::ThematicBreak(thematic_break) => self.thematic_break(thematic_break),
            // Nodes that are supported only as child of others
            node @ (mdast::Node::ListItem(_)
            | mdast::Node::TableCell(_)
            | mdast::Node::TableRow(_)) => Err(ToMinimadError::unsupported_child_node(node)),
            // Catch all for unsupported nodes
            other => Err(ToMinimadError::unsupported_node(other)),
        }
        .while_emitting(node)
    }
}

// -- Model switching and common functions --

impl<'a> Emitter<'a> {
    /// Temporarly change the content model to phrasing
    fn phrasing<R>(
        &mut self,
        style: minimad::CompositeStyle,
        spacing: bool,
        fun: impl FnOnce(&mut Self) -> R,
    ) -> R {
        // remove the old model, and if it was undefined set it to flow
        let mut old_model = self
            .model
            .take()
            .unwrap_or(ContentModel::Flow { spacing: false });
        if let ContentModel::Phrasing { style, compounds } = &mut old_model {
            // the old model was in the middle of a line. This can happen only in invalid ASTs, as the nodes that use `Phrasing`
            // as inner content should be called only in `Flow` model. Anyway, let's not mix up the content emitting that line
            self.lines.push(minimad::Line::Normal(Composite {
                style: *style,
                compounds: mem::take(compounds),
            }));
        }
        // put a spacing newline between flows element
        if old_model.need_spacing() {
            self.emptyline()
        }
        // set the new model as phrasing with the given style
        self.model = Some(ContentModel::Phrasing {
            style,
            compounds: vec![],
        });
        // call the inner function
        let res = fun(self);
        // put the old model back, settign spacing
        old_model.set_spacing(spacing);
        let residuals = mem::replace(&mut self.model, Some(old_model));
        // if some compounds remains, emit them
        if let Some(ContentModel::Phrasing { style, compounds }) = residuals {
            self.lines
                .push(minimad::Line::Normal(Composite { style, compounds }));
        }
        // return the function result
        res
    }

    /// Return the current line
    fn line(&mut self) -> &mut Vec<Compound<'a>> {
        match &mut self.model {
            Some(ContentModel::Phrasing {
                style: _,
                compounds,
            }) => compounds,
            model @ (None | Some(ContentModel::Flow { .. })) => {
                // If not phrasing (only in invalid ASTs), or if the model is undefined, assume we begin a new paragraph
                *model = Some(ContentModel::Phrasing {
                    style: minimad::CompositeStyle::Paragraph,
                    compounds: vec![],
                });
                let Some(ContentModel::Phrasing {
                    style: _,
                    compounds,
                }) = model
                else {
                    unreachable!()
                };
                compounds
            }
        }
    }

    /// Start a new line
    fn newline(&mut self) {
        match &mut self.model {
            Some(ContentModel::Phrasing { style, compounds }) => {
                self.lines.push(minimad::Line::Normal(Composite {
                    style: *style,
                    compounds: mem::take(compounds),
                }))
            }
            None | Some(ContentModel::Flow { .. }) => {
                // In this models a newline has no meaning. The method should only be called when in phrasing contexts.
                // Anyway ignoring to be lenient on malformed ASTs
            }
        }
    }

    /// Emit a empty line
    fn emptyline(&mut self) {
        self.lines.push(Line::new_paragraph(vec![]))
    }

    /// Emit formatted texts
    fn fmt_text(&mut self, value: &'a str, bold: bool, italic: bool, code: bool, strikeout: bool) {
        let mut lines = value.split("\r\n").flat_map(|l| l.split('\n'));
        if let Some(line) = lines.next() {
            self.line().push(Compound {
                src: line,
                bold,
                italic,
                code,
                strikeout,
            });
        }
        for line in lines {
            self.newline();
            self.line().push(Compound {
                src: line,
                bold,
                italic,
                code,
                strikeout,
            })
        }
    }
}
